services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    environment:
      - PI_IP=${PI_IP}

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - PI_IP=${PI_IP}

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    environment:
      - PI_IP=${PI_IP}

volumes:
  grafana-storage:

